### ISSUE TITLE
couple of steps

### ISSUE THREAD

**Issue by chovy** [chiefy/node-hockey-helper#1]
you need to have this:

FuckNeulion-v2.3.jar
https://mega.co.nz/#!5cRgwQ7S!kLvDXQrshwjBK9xM-zmu1RfNI91qoGb4Q3HMhSrZwJ4

You also need to add this line to /etc/hosts

127.0.0.1 nlsk.neulion.com

I would add these, maybe even include the FNeulion file so people don't have to go digging around.

**Comment by chiefy** [comment]
@chovy Thanks - yeah I forgot the /etc/hosts step. I will add the link, I was just concerned about DMCA takedowns.

**Comment by chovy** [comment]
Yeah, I wouldn't put the file in the repo then, but a link would help. Otherwise nobody will get it working.
