### ISSUE TITLE
Verify stuff works for 2015/16 season

### ISSUE THREAD

**Issue by chovy** [chiefy/node-hockey-helper#5]
```
$ hockey-helper FuckNeulionV2.3.jar
Checking for Java...
Found Java!
? Pick a game: SAN JOSE SHARKS	vs.	VANCOUVER CANUCKS	09:03 1st
? Home or away feed? Away
Uh-oh! Looks like there was a problem...
Could not run FuckNeulionV2: Failed at Step 3
```

**Comment by chiefy** [comment]
Thanks @chovy forgot it's almost that time of year :+1: I believe there's some pre-season on tonight, so I will check it out.

**Comment by chiefy** [comment]
@chovy I am running FN fine tonight, I think the above issue might be a pathing thing. Can you try again w/ `./FuckNeulionV2.3.jar`?

**Comment by chiefy** [comment]
@chovy closing this, let me know if you have issues.

**Comment by chovy** [comment]
It did not work for me.

**Comment by chiefy** [comment]
@chovy anything else to go on? I was using it last night w/ no problems? Did you get the latest FN?
